name: Build CR6606 完整版
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 安装依赖
        run: sudo apt update && sudo apt install build-essential libncurses-dev bison flex libssl-dev libelf-dev python3 -y

      - name: 拉取 LEDE 源码
        run: git clone https://gitee.com/coolsnowwolf/lede.git lede --depth 1

      - name: 拉取插件（国内镜像，无墙）
        run: |
          cd lede/package
          git clone https://gitee.com/kooljun/helloworld.git
          git clone https://gitee.com/kooljun/passwall2.git
          
      - name: 更新 feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 生成 CR6606 配置
        run: |
          cd lede
          cat > .config << EOF
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-cr6606=y
CONFIG_PACKAGE_luci-app-ssr-plus=y
CONFIG_PACKAGE_luci-app-passwall2=y
CONFIG_PACKAGE_luci-app-frpc=y
EOF
          make defconfig

      - name: 下载依赖
        run: cd lede && make download -j8

      - name: 开始编译
        run: cd lede && make -j4

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: cr6606-final
          path: lede/bin/targets/ramips/mt7621/*
